// Code generated by the dharitri-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

dharitri_wasm_node::wasm_endpoints! {
    digital_cash
    (
        fund
        withdraw
        claim
        amount
        deposit
    )
}

dharitri_wasm_node::wasm_empty_callback! {}
