// Code generated by the dharitri-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            2
// Async Callback:                       1
// Total number of exported functions:   4

#![no_std]

dharitri_wasm_node::wasm_endpoints! {
    child
    (
        issueWrappedMoa
        getWrappedMoaTokenIdentifier
        callBack
    )
}
