// Code generated by the dharitri-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]

dharitri_wasm_node::wasm_endpoints! {
    rewards_distribution
    (
        depositRoyalties
        raffle
        claimRewards
        computeClaimableAmount
        getRaffleId
        getCompletedRaffleIdCount
        getRoyalties
        getNftRewardPercent
        getWasClaimed
        getSeedNftMinterAddress
        getBrackets
        getLastRaffleEpoch
        getNftTokenId
    )
}

dharitri_wasm_node::wasm_empty_callback! {}
