// Code generated by the dharitri-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

dharitri_wasm_node::wasm_endpoints! {
    dct_transfer_with_fee
    (
        setExactValueFee
        setPercentageFee
        claimFees
        transfer
        getTokenFee
        getPaidFees
    )
}

dharitri_wasm_node::wasm_empty_callback! {}
