// Code generated by the dharitri-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            1
// Async Callback (empty):               1
// Total number of exported functions:   3

#![no_std]

dharitri_wasm_node::wasm_endpoints! {
    factorial
    (
        factorial
    )
}

dharitri_wasm_node::wasm_empty_callback! {}
