// Code generated by the dharitri-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

dharitri_wasm_node::wasm_endpoints! {
    lottery_dct
    (
        start
        createLotteryPool
        buy_ticket
        determine_winner
        status
        getLotteryInfo
        getLotteryWhitelist
    )
}

dharitri_wasm_node::wasm_empty_callback! {}
